### PR TITLE
Improved api for synchronous upload from URL.

### PR DESCRIPTION
**Pull request by caxap**

### CODE REVIEW

**Comment by dmitry-mukhin** [comment]
great, thanks!

**Comment by caxap** [comment]
When do you plan to update pip ?

**Comment by dmitry-mukhin** [comment]
I'll do it today.

**Comment by homm** [comment]
@caxap Just a tip: you can use particular git commit with pip, not required build from PYPI.
https://pip.pypa.io/en/latest/reference/pip_install.html#git

**Comment by caxap** [comment]
@homm yep, already using this way. Thanks.

**Comment by dmitry-mukhin** [comment]
it's live

**Comment by caxap** [comment]
Great, thanks!

**Pull request merged**
