### PR TITLE
clearable field added

### PR DESCRIPTION
**Pull request by dimaninc**

### CODE REVIEW

**Comment by dmitry-mukhin** [comment]
а все это дело в kwargs засунуть не получится?

**Comment by dimaninc** [comment]
может и можно... я по аналогии с manual_crop-ом делал

**Comment by dmitry-mukhin** [comment]
@homm what do you think? I haven't looked into it too much, but I believe `kwargs` are already doing something like this.

**Comment by dmitry-mukhin** [comment]
@dimaninc, it seems, that `clearable` is already covered by [this](https://github.com/uploadcare/pyuploadcare/blob/master/pyuploadcare/dj/forms.py#L65-L69)

**Comment by dimaninc** [comment]
it seems that you understand your own code so great :)

**Comment by dmitry-mukhin** [comment]
meh, it's not mine, see blame.

**Comment by dmitry-mukhin** [comment]
OK. apparently I'm not doing enough Django development these days :(

This PR is redundant as there is [builtin mechanism](https://docs.djangoproject.com/en/1.8/ref/forms/widgets/#customizing-widget-instances) in Django to provide widget with custom attributes.

So in your case, you should create a form and explicitly set `data-clearable` (or [any other](https://uploadcare.com/documentation/widget/#options)) attribute to one of it's fields. E.g.:

```python
from django import forms

from pyuploadcare.dj.forms import ImageField, FileWidget


class PhotoForm(forms.Form):
    photo = ImageField(widget=FileWidget(attrs={
        'data-clearable': '',
        'data-tabs': 'instagram webcam',
    }))

```

Also note, that if Field is marked as not required, `data-clearable` should be set by default.

Please let us know if you disagree.

**Pull request closed without merging**
